### ISSUE TITLE
[FEATURE REQUEST] $.post is not mocked by fauxjax

### ISSUE THREAD

**Issue by williamsbdev** [JarrodCTaylor/fauxjax#14]
It does not correctly mock a $.post. Would it possible to also "hijack" $.post and fauxjax these requests as well?

**Comment by JarrodCTaylor** [comment]
I don't use the jQuery shothand methods so I haven't thought about it before. I wouldn't want to only implement one of them `$.post` in this case and not have the others accounted for. Then if we include all five of them I fear that it would unnecessarily bloat the code base for little additional functionality. At this time I feel like this one is a pass for me unless there is a very compelling reason to think otherwise.

**Comment by dustinfarris** [comment]
I think $.post should be supported, and would not constitute bloat.  The post/get shortcuts are widely used in my experience.

I'm a little surprised it doesn't work already since they just proxy to the ajax method, see:

https://github.com/jquery/jquery/blob/9d1b989f20b550af3590691723b0620f6914626e/src/ajax.js#L788

+1 for implementing this from me.

**Comment by JarrodCTaylor** [comment]
Nice research on the link @dustinfarris. I agree I am kind of surprised that it doesn't work already. Given that you two constitute at least 30% of the user base that I am aware of I will give this a look over the weekend. No promises (haha I made a JavaScript joke) but looking at that link it seems like it could be done with limited bloat if that is the case then I will see what I can do.

**Comment by dustinfarris** [comment]
haha promises.  let me know if you need help with it.

**Comment by JarrodCTaylor** [comment]
Closed with 360480a5f5326b05661a69c381df42daa2f04813

This was surprisingly easy to implement. Fauxjax will now work with `$.post` `$.get` and `$.getJSON` 

Keep suggesting enhancements guys.

**Comment by williamsbdev** [comment]
Thank you so much! I was running into issues at work trying to upgrade (I believe 0.5.0) to 1.0.2. I appreciate all your hard work on this!
