### ISSUE TITLE
How to get at fauxHandlers (public api) to replace a previously mocked xhr?

### ISSUE THREAD

**Issue by toranb** [JarrodCTaylor/fauxjax#26]
Jarrod

first up - love the OSS project! thanks for all the work you put into this library! 

next up -often I run an xhr for a given url, but then later (in the same test) I need to hit that ajax request again and (sometimes) the data changes but when I stub it again the "first push" into fauxHandlers seems to win.

do you know of a work around to let me get this by url and verb (without using remove as it requires an index directly) ? In a "perfect world" I'd look up the ajax request I'd like to replace by url / verb and "push" over the top of it (or remove it first if you prefer).

would this be an option? if the capability doesn't exist yet would a new public api "to lookup" the handler by a given url/ and or verb be something I could add?

thanks again!

**Comment by toranb** [comment]
**update**

looks like I found my hook :)

$.fauxjax.fakedAjaxCalls().forEach(function(x) { console.log(x.url) });

**Comment by toranb** [comment]
sorry to reopen but this fakedAjaxCalls array provides a diff array index than what should actually be removed. I've pushed up a temp bower module w/ the api I'd like to have at some point. let me know your thoughts

```
    "fauxjax-toranb": "1.3.0"
```

https://github.com/toranb/fauxjax/blob/master/src/fauxjax.js#L59-L71

**Comment by JarrodCTaylor** [comment]
Is there any reason that the existing api and suggested workflow for clearing mocks is not adequate? 
https://github.com/JarrodCTaylor/fauxjax/wiki/Clearing-Fauxjax-Handlers

**Comment by toranb** [comment]
Not for my given situation

1) I cannot clear all because this is for a "re-mock" only helper (meaning -if you have an existing xhr, no problem. If you have an existing xhr using the same verb and url we need to "replace that" in favor of the new xhr mock

2) clear by id would "technically" be possible but the helper I have is an async test helper and I would need to create a global (ember) collection and keep track of the state to look it up later. Having this (new) api would allow me to avoid that stateful work and match only when the url/verb need an updated ajax mock

**Comment by JarrodCTaylor** [comment]
Yes clearing all seems to typically only be useful in the teardown. However, clearing by the reference to the mock has served me well in all cases so far. Unless there is a compelling / common reason that this new functionality would benefit the library that I am missing this feels a little superfluous to me. It is basically the same functionality that is there already but it will need to be much more verbose to implement and use.  

When deciding if a request should be mocked we take into consideration do the urls match, do the verbs match, does the data match, does the contentType match, do the headers match and finally is strictMatching enabled. 

To provide a way to remove a mock based on something other than a reference to the position of the original we would need to take all of those parts into consideration again, which is why it seems that it is a lot of work for little benefit. 

Do you have an example of your helper that makes it difficult to keep a reference to a specific mock that needs to be cleared? Perhaps we can retool the helper or maybe it will make the situation you are running into more clear to me.

**Comment by toranb** [comment]
Understood - here is an example of how I'm using this async helper (with ember) today

```js
function ajax(app, url, verb, data, headers, status, response) {
  Ember.run(function() {
    Ember.$.fauxjax.removeExisting(url, verb);
    var request = { url: url , method: verb };
    if (data) { 
        request.data = data;
        request.contentType = 'application/json';
    }
    Ember.$.fauxjax.new({
      request: request,
      response: {
        status: status,
        content: response
      }
    });
  });
  return app.testHelpers.wait();
}
```

I could try to keep track of each id as I mock it as you suggested (just a great deal of work to keep track of the state on a test/by test basis). I feel the level of effort is lower to add this api because w/out it I'll need to subclass a qunit module (for setup/teardown), add this async helper with access to the active ids (passed in as a function param) but ultimately it's your library (and your call) :)

Thanks for writing such a great OSS project!

**Comment by JarrodCTaylor** [comment]
Perhaps my head is just too much in Python and Clojure land for me to grok the value of this currently. I don't clearly see how this helper greatly reduces the amount of code that needs to be written, provides additional clarity or how using a reference to the specific ID returned when creating a fauxjax instance would add lines of code / work. 

Since this is not a feature that I am going to use I am not going to allocate the time right now to write / test / document it. However, given that the known user base of this project is so small (you account for a sizable portion of the users :smile:). If you feel it is valuable enough and want to write / test / document the function then we can review it and get it merged in.

**Comment by toranb** [comment]
I appreciate the offer and I'd love to add this api (plus another for FormData support -but that's another issue/ discussion altogether).

One question/ ask for help first - could you update the tests to work with a modern node setup? something like v0.12 or v4.1.1 ?

I tried to run the tests on v4.1.1 recently and it didn't go well :(

**Comment by JarrodCTaylor** [comment]
"Node: Yesterday's future marching on to break needed code today." - Jarrod

 I'm pretty sure I should be hired to be on their marketing team. 

I will give it a look this week.

**Comment by JarrodCTaylor** [comment]
Pulling the repo down fresh and doing an `npm install` and then running `grunt test` worked for both node v0.12.7 and v5.1.0

**Comment by toranb** [comment]
You sir is an animal (oh and you should start marketing for nodeJS - I'll get you a t-shirt or something next time we hang in person). I'll get after this after the holiday :)

**Comment by snewcomer** [comment]
@toranb Just wanted to circle back on this.  Would offer to help document / write tests for this feature if you would like.  Was there any blockers for getting this in there back in 2015 or just time?

**Comment by toranb** [comment]
@snewcomer I think @JarrodCTaylor is open to the pull request. We know the implementation (what you are using and what I'm using [here](https://github.com/toranb/ember-redux/blob/master/tests/helpers/start-app.js#L7) also)

If you have the bandwidth to submit a test driven pull request I'd be grateful - Jarrod you still interested in merging this much needed change?

**Comment by JarrodCTaylor** [comment]
I don't believe this issue is relevant any longer. As always reopen if new perspectives emerge.
