### ISSUE TITLE
`contentType` is not working when provided to `new`

### ISSUE THREAD

**Issue by dustinfarris** [JarrodCTaylor/fauxjax#6]
This causes fauxjax not to intercept the request:

```js
Ember.$.fauxjax.new({
  url: '/api/stuff',
  contentType: 'text/json',
  responseText: {'my': 'object'}
});
```

This, however, does work:

```js
Ember.$.fauxjax.settings.contentType = 'text/json';
Ember.$.fauxjax.new({
  url: '/api/stuff',
  responseText: {'my': 'object'}
});
```

**Comment by JarrodCTaylor** [comment]
I just wrote a test trying to mimic the issue you are having and I am unable to create it. I always use `application/json` which I believe is the recommend [MIME type for JSON](http://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type) so I have only attempted to duplicate this via the test and not in any of my apps. 

[Here is the test](https://github.com/JarrodCTaylor/fauxjax/blob/master/test/contentType.coffee#L59) let me know if you can write a failing test or if you have an example app that demonstrates the issue.

**Comment by JarrodCTaylor** [comment]
@dustinfarris were you able to get this working as desired?

**Comment by dustinfarris** [comment]
No, I still have to use the settings for this to work.  I am using `application/json` now, however, per your comment.

**Comment by JarrodCTaylor** [comment]
Is the test that I linked to above correctly simulating your setup?

**Comment by dustinfarris** [comment]
I will try to write a failing test for this once I get the tests running on my fork (see #10).

**Comment by dustinfarris** [comment]
See #11

**Comment by JarrodCTaylor** [comment]
There were a few things going on here. Taking a look at what you were doing it shouldn't have passed in either case. The default contentType for $.ajax is:
![screen shot 2015-03-21 at 7 48 59 am](https://cloud.githubusercontent.com/assets/4416952/6765536/d1a38188-cfb1-11e4-9db7-0f3f8b5eec8a.png)
So setting the fauxjax instance to have a contentType of `application/json` while the $.ajax request is using the default should not match. 

In addition to this there was a bug in fauxjax where the `$.fauxjax.settings.contentType` was not being checked when determining if the request should be mocked. Which is why it would (incorrectly) fake the request when you pulled it out of `$.fauxjax.new`

The version I just pushed 0.5.2 should now fail in both of the scenarios that you presented above. I added a few tests to make sure that there is adaquate coverage around this. 

If you are not setting the actual ajax request to use `application/json` then leave that off of your fauxjax and it will work as desired or add it to your ajax request as well if that is really what you want to use. 

Let me know if any of this doesn't make sense.

**Comment by dustinfarris** [comment]
Thanks for the explanation, it makes perfect sense.  I am, however, still confused about this definition of contentType from the fauxjax wiki:

> contentType: A string which specifies the content type for the _response_.

Extending your quote from the jQuery documentation above, the contentType used in $.ajax is defined as:

> When sending data to the server, use this content type. 

I was providing 'application/json' to `$.fauxjax.settings.contentType` because I understood it to be related to the _response_ data, as opposed to the request content.  It sounds like the definition in the fauxjax wiki needs to be updated—or am I missing something else?

**Comment by JarrodCTaylor** [comment]
Nope you are not missing anything. That was just an erroneous bit of information in the api docs. I updated it to now read. 
`contentType: A string which specifies the content type of the data being sent to the server.`

![nkrzawz](https://cloud.githubusercontent.com/assets/4416952/6765627/e1eb06e2-cfb6-11e4-9d08-648ac7afe440.jpg)

**Comment by dustinfarris** [comment]
Haha, gotcha.  :+1:
